### ISSUE TITLE
Add progress bar

### ISSUE THREAD

**Issue by KonradLinkowski** [KonradLinkowski/Voronoi#10]
Add progress bar to show that the process is going on

**Comment by zuhairnaqi** [comment]
Want progress bar while downloading image?
Btw downloading image not working.

**Comment by Error404m** [comment]
While changing number of dots or while photo uploading or photo downloading ??

**Comment by tianlangwu** [comment]
Can you assign it to me?

**Comment by ydegtyar** [comment]
I'll try to implement progress bar on image generation

**Comment by KonradLinkowski** [comment]
@Error404m downloading is instant so it doesn't need a progress bar
I want a progress bar when the calculation process goes on

**Comment by EnechukwuChibuike** [comment]
can I do this?

**Comment by Error404m** [comment]
Can you please assign this to me ??

**Comment by KonradLinkowski** [comment]
Guys, you can do it and I will make a look at this
