### ISSUE TITLE
There should be a download button

### ISSUE THREAD

**Issue by KonradLinkowski** [KonradLinkowski/Voronoi#2]
There should be a download button somewhere.
Maybe clicking the output image should result in download dialog.

**Comment by JoaoVSouto** [comment]
Hey! I can take this one :smile:

**Comment by manisacharya** [comment]
Hey @JoaoVSouto, sorry I was working into it but forgot to mention :disappointed:

**Comment by JoaoVSouto** [comment]
@manisacharya there is no problem buddy, it's alright :laughing:

**Comment by KonradLinkowski** [comment]
It's weird to see people fighting for taking the task in my repos :D
